version: "3.8"
services:
    app:
        build:
            args:
                user: vandao
                uid: 1000
            context: ./
            dockerfile: ./docker/app.dockerfile
        image: laravel-test
        container_name: laravel-test-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-test

    db:
        image: mysql:5.7
        container_name: laravel-test-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 4306:3306
        # volumes:
        #     - ./docker/sql:/docker-entrypoint-initdb.d
        networks:
            - laravel-test

    nginx:
        image: nginx:alpine
        container_name: laravel-test-nginx
        restart: unless-stopped
        ports:
            - 8080:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - laravel-test
networks:
    laravel-test:
        driver: bridge
